-- Authentication and user-profile schema for PostgreSQL 14+.
--
-- Passwords are intentionally stored as bcrypt hashes, not encrypted values.
-- Encryption is reversible; password hashing is the correct security practice.
-- This script uses pgcrypto's crypt() / gen_salt() functions.

BEGIN;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE account_status AS ENUM ('active', 'pending_verification', 'suspended', 'disabled', 'deleted');
CREATE TYPE authentication_event_type AS ENUM (
  'login_success', 'login_failed', 'logout', 'password_changed', 'password_reset_requested',
  'password_reset_completed', 'account_locked', 'account_unlocked', 'mfa_challenge', 'mfa_success'
);

CREATE TABLE app_user (
  user_id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  username              citext NOT NULL UNIQUE,
  email                 citext NOT NULL UNIQUE,
  first_name            varchar(100) NOT NULL,
  last_name             varchar(100) NOT NULL,
  display_name          varchar(200),
  phone_number          varchar(30),
  account_status        account_status NOT NULL DEFAULT 'pending_verification',
  email_verified_at     timestamptz,
  phone_verified_at     timestamptz,
  mfa_enabled           boolean NOT NULL DEFAULT false,
  privacy_policy_accepted_at timestamptz,
  marketing_opt_in      boolean NOT NULL DEFAULT false,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  deleted_at            timestamptz,
  CONSTRAINT ck_user_username CHECK (username ~ '^[a-zA-Z0-9._-]{3,100}$'),
  CONSTRAINT ck_user_email CHECK (email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
  CONSTRAINT ck_user_active_not_deleted CHECK (account_status <> 'deleted' OR deleted_at IS NOT NULL)
);

CREATE TABLE user_credential (
  user_id               uuid PRIMARY KEY REFERENCES app_user(user_id) ON DELETE CASCADE,
  -- bcrypt hash generated by crypt(plain_text, gen_salt('bf', 12)); never store plain text.
  password_hash         text NOT NULL,
  password_created_at   timestamptz NOT NULL DEFAULT now(),
  password_updated_at   timestamptz NOT NULL DEFAULT now(),
  password_expires_at   timestamptz,
  must_change_password  boolean NOT NULL DEFAULT false,
  failed_login_attempts integer NOT NULL DEFAULT 0 CHECK (failed_login_attempts >= 0),
  last_failed_login_at  timestamptz,
  locked_at             timestamptz,
  locked_until          timestamptz,
  last_login_at         timestamptz,
  last_login_ip         inet,
  last_login_user_agent text,
  password_reset_token_hash text,
  password_reset_expires_at timestamptz,
  password_reset_used_at timestamptz,
  CONSTRAINT ck_password_expiry CHECK (password_expires_at IS NULL OR password_expires_at > password_updated_at),
  CONSTRAINT ck_lock_window CHECK (locked_until IS NULL OR locked_at IS NOT NULL)
);

-- Keep old password hashes to prevent password reuse. Retain the last 10 in application logic.
CREATE TABLE password_history (
  password_history_id   bigserial PRIMARY KEY,
  user_id               uuid NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
  password_hash         text NOT NULL,
  created_at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_password_history_user_created ON password_history (user_id, created_at DESC);

CREATE TABLE authentication_event (
  authentication_event_id bigserial PRIMARY KEY,
  user_id               uuid REFERENCES app_user(user_id) ON DELETE SET NULL,
  event_type            authentication_event_type NOT NULL,
  occurred_at           timestamptz NOT NULL DEFAULT now(),
  ip_address            inet,
  user_agent            text,
  detail                jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX ix_auth_event_user_occurred ON authentication_event (user_id, occurred_at DESC);
CREATE INDEX ix_auth_event_type_occurred ON authentication_event (event_type, occurred_at DESC);

-- Automatically maintain the user profile timestamp.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_app_user_updated_at
BEFORE UPDATE ON app_user
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Use this procedure when registering a user. The caller should verify email before activation.
CREATE OR REPLACE FUNCTION register_user(
  p_username text,
  p_email text,
  p_first_name text,
  p_last_name text,
  p_password text
) RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE
  v_user_id uuid;
BEGIN
  IF length(p_password) < 12 THEN
	RAISE EXCEPTION 'Password must contain at least 12 characters';
  END IF;

  INSERT INTO app_user (username, email, first_name, last_name)
  VALUES (trim(p_username), lower(trim(p_email)), trim(p_first_name), trim(p_last_name))
  RETURNING user_id INTO v_user_id;

  INSERT INTO user_credential (user_id, password_hash)
  VALUES (v_user_id, crypt(p_password, gen_salt('bf', 12)));

  RETURN v_user_id;
END;
$$;

-- Returns one generic result for bad credentials, unknown accounts, inactive accounts and locked accounts.
-- Lockout policy: five consecutive failed attempts locks the account for 30 minutes.
CREATE OR REPLACE FUNCTION authenticate_user(
  p_login text,
  p_password text,
  p_ip_address inet DEFAULT NULL,
  p_user_agent text DEFAULT NULL
) RETURNS TABLE (authenticated boolean, user_id uuid, result text) LANGUAGE plpgsql AS $$
DECLARE
  v_user app_user%ROWTYPE;
  v_credential user_credential%ROWTYPE;
  v_new_attempt_count integer;
BEGIN
  SELECT u.* INTO v_user
  FROM app_user u
  WHERE u.username = p_login OR u.email = p_login
  LIMIT 1;

  IF NOT FOUND THEN
	INSERT INTO authentication_event (event_type, ip_address, user_agent, detail)
	VALUES ('login_failed', p_ip_address, p_user_agent, jsonb_build_object('login', p_login));
	RETURN QUERY SELECT false, NULL::uuid, 'Invalid credentials';
	RETURN;
  END IF;

  SELECT c.* INTO v_credential FROM user_credential c WHERE c.user_id = v_user.user_id FOR UPDATE;
  IF v_user.account_status <> 'active' OR (v_credential.locked_until IS NOT NULL AND v_credential.locked_until > now()) THEN
	INSERT INTO authentication_event (user_id, event_type, ip_address, user_agent)
	VALUES (v_user.user_id, 'login_failed', p_ip_address, p_user_agent);
	RETURN QUERY SELECT false, NULL::uuid, 'Invalid credentials';
	RETURN;
  END IF;

  IF v_credential.password_hash = crypt(p_password, v_credential.password_hash) THEN
	UPDATE user_credential
	SET failed_login_attempts = 0, last_failed_login_at = NULL, locked_at = NULL, locked_until = NULL,
		last_login_at = now(), last_login_ip = p_ip_address, last_login_user_agent = p_user_agent
	WHERE user_credential.user_id = v_user.user_id;
	INSERT INTO authentication_event (user_id, event_type, ip_address, user_agent)
	VALUES (v_user.user_id, 'login_success', p_ip_address, p_user_agent);
	RETURN QUERY SELECT true, v_user.user_id, 'Authenticated';
	RETURN;
  END IF;

  v_new_attempt_count := v_credential.failed_login_attempts + 1;
  UPDATE user_credential
  SET failed_login_attempts = v_new_attempt_count, last_failed_login_at = now(),
	  locked_at = CASE WHEN v_new_attempt_count >= 5 THEN now() ELSE locked_at END,
	  locked_until = CASE WHEN v_new_attempt_count >= 5 THEN now() + interval '30 minutes' ELSE locked_until END
  WHERE user_credential.user_id = v_user.user_id;
  INSERT INTO authentication_event (user_id, event_type, ip_address, user_agent)
  VALUES (v_user.user_id, 'login_failed', p_ip_address, p_user_agent);
  IF v_new_attempt_count >= 5 THEN
	INSERT INTO authentication_event (user_id, event_type, ip_address, user_agent)
	VALUES (v_user.user_id, 'account_locked', p_ip_address, p_user_agent);
  END IF;
  RETURN QUERY SELECT false, NULL::uuid, 'Invalid credentials';
END;
$$;

-- Changes a password, keeps its prior hash, and rejects reuse of the 10 most recent passwords.
CREATE OR REPLACE FUNCTION change_password(
  p_user_id uuid,
  p_current_password text,
  p_new_password text
) RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  v_credential user_credential%ROWTYPE;
BEGIN
  IF length(p_new_password) < 12 THEN
	RAISE EXCEPTION 'Password must contain at least 12 characters';
  END IF;

  SELECT c.* INTO v_credential FROM user_credential c WHERE c.user_id = p_user_id FOR UPDATE;
  IF NOT FOUND OR v_credential.password_hash <> crypt(p_current_password, v_credential.password_hash) THEN
	RAISE EXCEPTION 'Current password is invalid';
  END IF;
  IF EXISTS (
	SELECT 1 FROM password_history h
	WHERE h.user_id = p_user_id AND h.password_hash = crypt(p_new_password, h.password_hash)
  ) OR v_credential.password_hash = crypt(p_new_password, v_credential.password_hash) THEN
	RAISE EXCEPTION 'Password was used recently';
  END IF;

  INSERT INTO password_history (user_id, password_hash) VALUES (p_user_id, v_credential.password_hash);
  DELETE FROM password_history
  WHERE password_history_id IN (
	SELECT password_history_id FROM password_history
	WHERE user_id = p_user_id
	ORDER BY created_at DESC
	OFFSET 10
  );
  UPDATE user_credential
  SET password_hash = crypt(p_new_password, gen_salt('bf', 12)), password_updated_at = now(),
	  password_expires_at = NULL, must_change_password = false,
	  password_reset_token_hash = NULL, password_reset_expires_at = NULL, password_reset_used_at = now()
  WHERE user_credential.user_id = p_user_id;
  INSERT INTO authentication_event (user_id, event_type) VALUES (p_user_id, 'password_changed');
END;
$$;

-- Safe reporting view: exposes no password or reset-token hashes.
CREATE VIEW user_security_status AS
SELECT
  u.user_id, u.username, u.email, u.account_status, u.email_verified_at, u.mfa_enabled,
  c.last_login_at, c.last_failed_login_at, c.failed_login_attempts, c.locked_at, c.locked_until,
  c.password_created_at, c.password_updated_at,
  EXTRACT(day FROM now() - c.password_updated_at)::integer AS days_since_password_updated,
  EXTRACT(day FROM now() - c.password_created_at)::integer AS days_since_password_created,
  c.must_change_password, c.password_expires_at
FROM app_user u
JOIN user_credential c ON c.user_id = u.user_id;

COMMIT;

-- Example usage:
-- SELECT register_user('jane.doe', 'jane@example.com', 'Jane', 'Doe', 'a-long-unique-password');
-- UPDATE app_user SET account_status = 'active', email_verified_at = now() WHERE username = 'jane.doe';
-- SELECT * FROM authenticate_user('jane.doe', 'a-long-unique-password', '203.0.113.10', 'Mozilla/5.0');
-- SELECT * FROM user_security_status;
